### ISSUE TITLE
Missing steps in the After Installation portion

### ISSUE THREAD

**Issue by nzampella** [KI7MT/jtsdk-win#2]
Greg,

You're missing a few lines from the various Windows version instructions:

XP/Vista/Win7
svn switch ^^/jtsdk-win/tags/jtsdk-win-2.0.5
Close JTSDK-Maint

Win8/10
svn switch --accept tc ^^/jtsdk-win/tags/jtsdk-win-2.0.5
Close JTSDK-Maint

I've noticed a few people having issues as this was not done.

**Comment by KI7MT** [comment]
Hi Nzampella,

Thanks for the catch! I'll go through the docs, and ensure they are consistent.

Greg.

**Comment by jmccusker** [comment]
Greg, 
The current basic compiling steps fail when I try to compile WSJTX in the JTSDK-QT window.  I'm using Windows 10  and have installed everything using the JTSDK 2.0 installer from SourceForge.  I get the following error related to asciidoctor which doesn't appear to be installed anywhere:

-- Building wsjtx-1.7.1-devel
-- ******************************************************
-- Building for for: Windows-x86
-- ******************************************************
-- Boost version: 1.63.0
-- Found hamlib
-- hamlib_INCLUDE_DIRS: C:/JTSDK/hamlib3/include
-- hamlib_LIBRARIES: -LC:/JTSDK/hamlib3/lib;-lhamlib;-lws2_32
-- hamlib_LIBRARY_DIRS: C:/JTSDK/hamlib3/lib
CMake Error at doc/CMakeLists.txt:125 (message):
  asciidoctor is required to build the documentation

Any idea what's going wrong here?

73,

Jim KC3FFX
