### ISSUE TITLE
After upgrading to 2.0.5 JTSDK opens but then closes.

### ISSUE THREAD

**Issue by wa4pgm** [KI7MT/jtsdk-win#3]
After upgrading to 2.0.5, JTSDK opens but then closes within a second or two. I uninstalled JTSDK then reinstalled but get the same results.

Any thoughts?
Thanks,
Kyle, WA4PGM

**Comment by jmccusker** [comment]
Kyle,

Have you tried uninstalling and reinstalling recently?  I had a similar issue last night while playing with the SourceForge JTSDK installer.  I simply uninstalled everything and reinstalled again.

  --Jim KC3FFX

**Comment by wa4pgm** [comment]
Thanks Jim,
I forgot what I did to get it working but now each time I try to build 
the latest I get errors and it never finishes so I gave up.
Hamlib3 builds but build-wstx rinstall I get errors.
HNY73,
Kyle

**Comment by jmccusker** [comment]
Hi Kyle,

I just reinstalled everything after realizing that I had to install 4
additional updates before doing anything.  I'm compiling hamlib3 right now
and will let you know if I'm able to compile wstx.  The latest directions
seem to be at SourceForge:

https://sourceforge.net/projects/jtsdk/files/win32/2.0.0/

Crossing fingers....

 --Jim KC3FFX

**Comment by jmccusker** [comment]
Kyle,

Well, I followed the directions and ran into a build issue but was able to
find someone who told me the workaround.  Here it is in case you want to
try to build everything.  I'd suggest uninstalling and reinstalling
everything.  You then just need to edit one file:

Edit *\JTSDK\hamlib3-qt55\lib\pkgconfig\hamlib.pc*
Remove the *libusb* entry on the "*Requires.private:*" line. Leave the
Requries tag though.

This seemed to do the trick for me and I'm able to build everything now.

As with any active software development the documentation is always the
last thing to get updated.  Luckily there seem to be a lot of the
developers available during the holiday!

Good luck,

Jim McCusker
KC3FFX

**Comment by KI7MT** [comment]
Hello All, 

I am working on the fix for this. It's in testing now. In short, libusb-1.0 needed to be added to JTSDK then included with the msys-build-hamlib3 script.

73's
Greg, KI7MT
