### ISSUE TITLE
Basic Compiling of WSJTX fails (asciidoctor missing)

### ISSUE THREAD

**Issue by jmccusker** [KI7MT/jtsdk-win#4]
Greg,
The current basic compiling steps fail when I try to compile WSJTX in the JTSDK-QT window. I'm using Windows 10 and have installed everything using the JTSDK 2.0 installer from SourceForge. I get the following error related to asciidoctor which doesn't appear to be installed anywhere:

-- Building wsjtx-1.7.1-devel
-- ******************************************************
-- Building for for: Windows-x86
-- ******************************************************
-- Boost version: 1.63.0
-- Found hamlib
-- hamlib_INCLUDE_DIRS: C:/JTSDK/hamlib3/include
-- hamlib_LIBRARIES: -LC:/JTSDK/hamlib3/lib;-lhamlib;-lws2_32
-- hamlib_LIBRARY_DIRS: C:/JTSDK/hamlib3/lib
CMake Error at doc/CMakeLists.txt:125 (message):
asciidoctor is required to build the documentation

Any idea what's going wrong here?

73,

Jim KC3FFX

**Comment by KI7MT** [comment]
Hi Jim,

You need to install JTSDK Update-3, as that provides Ruby and Asciidoctor.

73's
Greg, KI7MT

**Comment by jmccusker** [comment]
Thanks Greg.  I was following bad directions and failed to install all 4 of
the updates.  Once I did that I was about to get things going, but I also
needed to remove that library reference I recently posted.  Once I did this
I was able to build WSJT-X v1.8.1-rc1 successfully!   Just need to tweak
the directions on SourceForge or get that fix out asap.  :-)

Thanks for the great work!

 --Jim KC3FFX

**Comment by KI7MT** [comment]
I think this is resolved now. To test the patch:

Open JTSDK Maint
update
upgrade

You should be on Revision: JTSDK 2.0.6-0 release 715

close JTSDK-Maint
Open JTSDK-QT
build-hamlib3
build-wsjtx rinstall

Let me know if this does not resolve the problem.

73's
Greg, KI7MT

**Comment by jmccusker** [comment]
Okay, thanks.  I'm building it now and will update you shortly.

 --Jim

**Comment by jmccusker** [comment]
Greg,

All is compiling now.  Thanks for the quick fix!

 --Jim KC3FFX
